# TA Watcher 配置文件
# 这是一个完整的示例配置，展示了所有可配置选项

# Binance API 配置（使用公开API，无需密钥）
binance:
  # 限流配置
  rate_limit:
    requests_per_minute: 1200       # 每分钟最大请求数
    retry_delay: 2s                 # 重试延迟
    max_retries: 3                  # 最大重试次数

# 监控配置
watcher:
  interval: 5m                      # 监控间隔
  max_workers: 10                   # 最大工作协程数
  buffer_size: 100                  # 缓冲区大小
  log_level: "info"                 # 日志级别: debug, info, warn, error
  enable_metrics: true              # 是否启用指标收集

# 通知配置
notifiers:
  # 邮件通知
  email:
    enabled: false                  # 是否启用邮件通知
    smtp:
      host: "smtp.gmail.com"        # SMTP服务器地址
      port: 587                     # SMTP端口
      username: ""                  # SMTP用户名
      password: ""                  # SMTP密码（建议使用应用专用密码）
      tls: true                     # 是否使用TLS加密
    from: ""                        # 发送者邮箱
    to:                             # 接收者邮箱列表
      - "zhangjingyao666@gmail.com"
    subject: "TA Watcher Alert - {{.Asset}} {{.Level}}"  # 邮件主题模板
    template: ""                    # 邮件内容模板（留空使用默认）
  
  # 飞书通知
  feishu:
    enabled: false                  # 是否启用飞书通知
    webhook_url: ""                 # 飞书机器人Webhook URL
    secret: ""                      # 签名密钥（可选）
    template: ""                    # 消息模板（留空使用默认）
  
  # 微信通知
  wechat:
    enabled: false                  # 是否启用微信通知
    webhook_url: ""                 # 企业微信机器人Webhook URL
    template: ""                    # 消息模板（留空使用默认）

# 监控资产列表
assets:
  - "BTCUSDT"                       # 比特币/USDT
  - "ETHUSDT"                       # 以太坊/USDT
  - "BNBUSDT"                       # 币安币/USDT
  - "ADAUSDT"                       # 卡尔达诺/USDT
  - "SOLUSDT"                       # Solana/USDT

# 策略配置
strategies:
  # RSI策略
  - name: "rsi_strategy"
    enabled: true                   # 是否启用
    assets:                         # 监控的资产
      - "BTCUSDT"
      - "ETHUSDT"
    interval: "1h"                  # K线间隔
    params:                         # 策略参数
      period: 14                    # RSI周期
      oversold: 30                  # 超卖阈值
      overbought: 70                # 超买阈值
      
  # MACD策略
  - name: "macd_strategy"
    enabled: true
    assets:
      - "BTCUSDT"
      - "ETHUSDT"
      - "BNBUSDT"
    interval: "4h"
    params:
      fast_period: 12               # 快线周期
      slow_period: 26               # 慢线周期
      signal_period: 9              # 信号线周期
      
  # 移动平均线金叉策略
  - name: "golden_cross"
    enabled: false                  # 暂时禁用
    assets:
      - "BTCUSDT"
    interval: "1d"
    params:
      short_period: 50              # 短期均线
      long_period: 200              # 长期均线
      
  # 价格突破策略
  - name: "price_breakout"
    enabled: true
    assets:
      - "BTCUSDT"
      - "ETHUSDT"
    interval: "15m"
    params:
      lookback_period: 20           # 回看周期
      breakout_threshold: 0.02      # 突破阈值（2%）
      volume_multiplier: 1.5        # 成交量倍数
