version: "3.8"

services:
  ta-watcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ta-watcher
    restart: unless-stopped

    # Map .env file contents to container environment variables
    env_file:
      - .env

    # Additional environment variables if needed
    environment:
      - TZ=Asia/Shanghai
      - LOG_LEVEL=info

    # Mount config file if you want to use custom config
    volumes:
      - ./config.yaml:/config.yaml:ro
      # Optionally mount logs directory
      - ./logs:/logs

    # Health check
    healthcheck:
      test: ["CMD", "/ta-watcher", "-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Optional: Add a network for isolation
networks:
  default:
    name: ta-watcher-network
